/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as CevremRouteImport } from './routes/cevrem'
import { Route as DepremRouteImport } from './routes/deprem'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as GuvenliRouteImport } from './routes/guvenli'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as KullanimSartlariRouteImport } from './routes/kullanim-sartlari'
import { Route as PolitikalarRouteImport } from './routes/politikalar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const CevremRoute = CevremRouteImport.update({
  id: '/cevrem',
  path: '/cevrem',
  getParentRoute: () => rootRouteImport,
} as any)
const DepremRoute = DepremRouteImport.update({
  id: '/deprem',
  path: '/deprem',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenliRoute = GuvenliRouteImport.update({
  id: '/guvenli',
  path: '/guvenli',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimSartlariRoute = KullanimSartlariRouteImport.update({
  id: '/kullanim-sartlari',
  path: '/kullanim-sartlari',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikalarRoute = PolitikalarRouteImport.update({
  id: '/politikalar',
  path: '/politikalar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/cevrem': typeof CevremRoute
  '/deprem': typeof DepremRoute
  '/giris': typeof GirisRoute
  '/guvenli': typeof GuvenliRoute
  '/kayit': typeof KayitRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/politikalar': typeof PolitikalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/cevrem': typeof CevremRoute
  '/deprem': typeof DepremRoute
  '/giris': typeof GirisRoute
  '/guvenli': typeof GuvenliRoute
  '/kayit': typeof KayitRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/politikalar': typeof PolitikalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/cevrem': typeof CevremRoute
  '/deprem': typeof DepremRoute
  '/giris': typeof GirisRoute
  '/guvenli': typeof GuvenliRoute
  '/kayit': typeof KayitRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/politikalar': typeof PolitikalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayarlar'
    | '/cevrem'
    | '/deprem'
    | '/giris'
    | '/guvenli'
    | '/kayit'
    | '/kullanim-sartlari'
    | '/politikalar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayarlar'
    | '/cevrem'
    | '/deprem'
    | '/giris'
    | '/guvenli'
    | '/kayit'
    | '/kullanim-sartlari'
    | '/politikalar'
  id:
    | '__root__'
    | '/'
    | '/ayarlar'
    | '/cevrem'
    | '/deprem'
    | '/giris'
    | '/guvenli'
    | '/kayit'
    | '/kullanim-sartlari'
    | '/politikalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  CevremRoute: typeof CevremRoute
  DepremRoute: typeof DepremRoute
  GirisRoute: typeof GirisRoute
  GuvenliRoute: typeof GuvenliRoute
  KayitRoute: typeof KayitRoute
  KullanimSartlariRoute: typeof KullanimSartlariRoute
  PolitikalarRoute: typeof PolitikalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cevrem': {
      id: '/cevrem'
      path: '/cevrem'
      fullPath: '/cevrem'
      preLoaderRoute: typeof CevremRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deprem': {
      id: '/deprem'
      path: '/deprem'
      fullPath: '/deprem'
      preLoaderRoute: typeof DepremRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenli': {
      id: '/guvenli'
      path: '/guvenli'
      fullPath: '/guvenli'
      preLoaderRoute: typeof GuvenliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-sartlari': {
      id: '/kullanim-sartlari'
      path: '/kullanim-sartlari'
      fullPath: '/kullanim-sartlari'
      preLoaderRoute: typeof KullanimSartlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politikalar': {
      id: '/politikalar'
      path: '/politikalar'
      fullPath: '/politikalar'
      preLoaderRoute: typeof PolitikalarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  CevremRoute: CevremRoute,
  DepremRoute: DepremRoute,
  GirisRoute: GirisRoute,
  GuvenliRoute: GuvenliRoute,
  KayitRoute: KayitRoute,
  KullanimSartlariRoute: KullanimSartlariRoute,
  PolitikalarRoute: PolitikalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
